# Generated by Django 5.0.2 on 2024-04-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='frame',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
